[pytest]
testpaths = tests
addopts = --cov=app --cov=main --cov-report=term-missing
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

markers =
    e2e: marks tests as end-to-end (run with '-m e2e', skip with '-m "not e2e"')

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::ResourceWarning
